### ISSUE TITLE
pls help me out in this

### ISSUE THREAD

**Issue by govindsaudagar** [edgeimpulse/linux-sdk-python#13]
File "/home/robotics/linux-sdk-python/examples/audio/classify.py", line 5, in <module>
    from edge_impulse_linux.audio import AudioImpulseRunner
ModuleNotFoundError: No module named 'edge_impulse_linux'

**Comment by ShawnHymel** [comment]
@govindsaudagar you need to install the Linux Python SDK as per these directions: [https://docs.edgeimpulse.com/docs/edge-impulse-for-linux/linux-python-sdk](https://docs.edgeimpulse.com/docs/edge-impulse-for-linux/linux-python-sdk).

**Comment by mmajchrzycki** [comment]
Resolved. For any other assistance, please visit our forum https://forum.edgeimpulse.com/
