### ISSUE TITLE
audio.py -- recording buffer 

### ISSUE THREAD

**Issue by Aishaj** [edgeimpulse/linux-sdk-python#15]
Hello, 

I'm working on an example 

1- When editing the file audio.py under (edge_impulse_linux) I'm not seeing the change reflected. Am I editing the right file? 
2- So the model is running and classifies correctly, however, if the classification is above .80 I’m performing certain actions (running google home) and then performing time.sleep(10). I noticed that the system records whatever google home is saying and also records during sleep time, so it keeps predicting wrong input.  How can I delete whatever is in the buffer after performing my actions?

**Comment by mmajchrzycki** [comment]
Hi @Aishaj 

> 1- When editing the file audio.py under (edge_impulse_linux) I'm not seeing the change reflected. Am I editing the right file?

What do you mean there are no changes? What do you change exactly?

> How can I delete whatever is in the buffer after performing my actions?

There are two options:
1. Stop Impulse runner
2. Clear `features` before performing further actions.

I'm closing the discussion here as it is not an issue with our SDK. For any further assistance, please use our support forum https://forum.edgeimpulse.com/
