### ISSUE TITLE
Checking on RGB/BGR issue

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/linux-sdk-python#17]
From a user: https://forum.edgeimpulse.com/t/raspberry-pi-camera-script-using-grayscale/7682

If `get_features_from_images()` expects RGB, then shouldn't the conversion `cv2.cvtColor()` use `cv2.COLOR_RGB2GRAY`?

```
    # This expects images in RGB format (not BGR)
    def get_features_from_image(self, img, crop_direction_x='center', crop_direction_y='center'):
        features = []

       ...

        if self.isGrayscale:
            cropped = cv2.cvtColor(cropped, cv2.COLOR_BGR2GRAY)
            pixels = np.array(cropped).flatten().tolist()

            for p in pixels:
               ...
```

**Comment by Alex-EEE** [comment]
we generally expect the Image block to convert from 3 channels down to 1.  On Linux, I'm not even sure any capture device will give you a true greyscale (ie 1B / pixel) output, but rather, you'll just the RGB equivalent
