### ISSUE TITLE
Jetson Nano (Ubuntu 18/aarch64) - ERROR: Could not find a version that satisfies the requirement edge_impulse_linux

### ISSUE THREAD

**Issue by kaisark** [edgeimpulse/linux-sdk-python#4]
Is there a pip python edge_impulse_linux package for the Jetson Nano (Ubuntu 18/aarch64)? Pip3 could not locate the package:

(py36dl) username@nano:~/edgeimpulse$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 

(py36dl) username@nano:~/edgeimpulse$ pip3 install edge_impulse_linux
ERROR: Could not find a version that satisfies the requirement edge_impulse_linux
ERROR: No matching distribution found for edge_impulse_linux
WARNING: You are using pip version 21.0.1; however, version 21.1 is available.
You should consider upgrading via the '/home/username/.virtualenvs/py36dl/bin/python -m pip install --upgrade pip' command.

**Comment by janjongboom** [comment]
Hi @kaisark, sorry, don't see updates on this repo automatically. You'll need Python 3.7 here. `apt install -y python3.7` should work.
